kind: source
spec:
  name: aws
  path: cloudquery/aws
  version: "v9.1.1" # latest version of aws plugin
  tables: ["*"]
  destinations: ["postgresql"]
---
kind: destination
spec:
  name: postgresql
  path: cloudquery/postgresql
  version: "v2.0.1" # latest version of postgresql plugin
  spec:
    connection_string: ${CQ_DSN}
