cloudquery:
  providers:
  - name: aws
    version: latest
  connection:
    dsn: "${DSN}"
providers:
- name: aws
  configuration:
    # Optional, Repeated. Add an accounts block for every account you want to assume-role into and fetch data from.
    # accounts:
    #   - id: <UNIQUE ACCOUNT IDENTIFIER>
    # Optional. Role ARN we want to assume when accessing this account
    #     role_arn: < YOUR_ROLE_ARN >
    # Optional. Named profile in config or credential file from where CQ should grab credentials
    #     local_profile: < PROFILE_NAME >
    # Optional. by default assumes all regions
    # regions:
    #   - us-east-1
    #   - us-west-2
    # Optional. Enable AWS SDK debug logging.
    #   aws_debug: false
    # The maximum number of times that a request will be retried for failures. Defaults to 10 retry attempts.
    # max_retries: 10
    # The maximum back off delay between attempts. The backoff delays exponentially with a jitter based on the number of attempts. Defaults to 30 seconds.
    # max_backoff: 30
  resources:
  # list of resources to fetch
  - "*"
