kind: source
spec:
  name: aws
  path: cloudquery/aws
  version: "v4.15.0" # latest version of aws plugin
  tables: ["*"]
  destinations: ["postgresql"]
---
kind: destination
spec:
  name: postgresql
  path: cloudquery/postgresql
  version: "v1.7.8" # latest version of postgresql plugin
  spec:
    connection_string: ${CQ_DSN}
