name: Pre-Commit

on:
  pull_request:
    branches:
      - main

jobs:
  collectInputs:
    name: Collect workflow inputs
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.dirs.outputs.directories }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get root directories
        id: dirs
        uses: clowdhaus/terraform-composite-actions/directories@v1.6.0
  preCommitMinVersions:
    name: Min TF pre-commit
    needs: collectInputs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(needs.collectInputs.outputs.directories) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform min/max versions
        id: minMax
        uses: clowdhaus/terraform-min-max@v1.1.1
        with:
          directory: ${{ matrix.directory }}

      - name: Pre-commit Terraform ${{ steps.minMax.outputs.minVersion }}
        # Run only validate pre-commit check on min version supported
        if: ${{ matrix.directory !=  '.' }}
        uses: clowdhaus/terraform-composite-actions/pre-commit@v1.6.0
        with:
          terraform-version: ${{ steps.minMax.outputs.minVersion }}
          args: "terraform_validate --color=always --show-diff-on-failure --files ${{ matrix.directory }}/*"

      - name: Pre-commit Terraform ${{ steps.minMax.outputs.minVersion }}
        # Run only validate pre-commit check on min version supported
        if: ${{ matrix.directory ==  '.' }}
        uses: clowdhaus/terraform-composite-actions/pre-commit@v1.6.0
        with:
          terraform-version: ${{ steps.minMax.outputs.minVersion }}
          args: "terraform_validate --color=always --show-diff-on-failure --files $(ls *.tf)"

  preCommitMaxVersion:
    name: Max TF pre-commit
    runs-on: ubuntu-latest
    needs: collectInputs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        if: github.actor != 'cq-bot'
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Checkout
        uses: actions/checkout@v3
        if: github.actor == 'cq-bot'
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          token: ${{ secrets.GH_CQ_BOT }}

      - name: Terraform min/max versions
        id: minMax
        uses: clowdhaus/terraform-min-max@v1.1.1

      - name: Pre-commit Terraform ${{ steps.minMax.outputs.maxVersion }}
        if: github.actor == 'cq-bot'
        uses: clowdhaus/terraform-composite-actions/pre-commit@v1.6.0
        continue-on-error: true
        with:
          terraform-version: ${{ steps.minMax.outputs.maxVersion }}
          terraform-docs-version: v0.16.0
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: github.actor == 'cq-bot'
        with:
          commit_message: "chore: Add pre-commit changes"
      - name: Pre-commit Terraform ${{ steps.minMax.outputs.maxVersion }}
        uses: clowdhaus/terraform-composite-actions/pre-commit@v1.6.0
        if: github.actor != 'cq-bot'
        with:
          terraform-version: ${{ steps.minMax.outputs.maxVersion }}
          terraform-docs-version: v0.16.0
